### ISSUE TITLE
ICHNOS version?

### ISSUE THREAD

**Issue by spgerenday** [giorgk/ichnos#4]
I notice that ichnos_options.h states that the version is 0.2.10; however, ichnos.exe displays the message
 |------------------|
|      ICHNOS      |
| Version : 0.1.10 |
|    by  giorgk    |
|------------------|
It also does not seem to recognize the options for what I assume is version 0.2.10. Which version should it be?

**Comment by giorgk** [comment]
The last 2-3 weeks I worked on a major update with the goal to support transient particle tracking. As a result a lot of code has been restructured and the input options changed a bit. I have also added a version option so that there is a way to test if the correct input set is used for the right version. At this point the documentation has been updated to the 0.2.10 version but I have not uploaded the binary because I haven't finished the debugging mainly for the multicore version.

**Comment by spgerenday** [comment]
Thanks. For version 0.1.10 steady state, should the velocity file be organized X Y Z PROC DIAM RATIO VX VY VZ or X Y Z VX VY VZ PROC DIAM RATIO. I seem to recall earlier versions of the documentation had the velocities last, and I seem to get exe stopped working errors when I put velocities in the middle. Will that be how it is arranged for version 0.2.10?

**Comment by giorgk** [comment]
I think that the format previously for the steady state was 
X Y Z PROC VX VY VZ CONST DIAM RATIO
Where for single processor PROC is 0. CONST can be any integer and it is ignored. It was a remnant of another code [redist](https://github.com/giorgk/redist).

Anyway I'm planning next week to compile and update the new version
